services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    expose:
      - "8080"
    environment:
      - PORT=8080
    networks:
      - microservices-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    expose:
      - "8081"
    environment:
      - PORT=8081
      - USER_SERVICE_URL=http://user-service:8080
    depends_on:
      - user-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge